name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 

        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Check if the issue exists in the latest version
        - Test with minimal reproduction steps

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues
          required: true
        - label: I am using the latest version of DeepLX
          required: true
        - label: I have checked the documentation
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Configure DeepLX with...
        2. Send a request to...
        3. Observe that...
      value: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: minimal-example
    attributes:
      label: Minimal Reproduction Example
      description: Provide a minimal code example that reproduces the issue
      placeholder: |
        // Minimal example
        const response = await fetch('/translate', {
          method: 'POST',
          body: JSON.stringify({
            text: 'Hello world',
            target_lang: 'ES'
          })
        });
      render: typescript

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running DeepLX?
      options:
        - Cloudflare Workers
        - Local development
        - Docker
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: DeepLX Version
      description: What version of DeepLX are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: e.g., 18.17.0

  - type: input
    id: wrangler-version
    attributes:
      label: Wrangler Version
      description: What version of Wrangler are you using? (if applicable)
      placeholder: e.g., 4.25.0

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Include any relevant error messages or logs
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: network-info
    attributes:
      label: Network Information
      description: Include request/response details if relevant
      placeholder: |
        Request:
        POST /translate
        Content-Type: application/json

        Response:
        Status: 500
        Body: {"error": "..."}
      render: http

  - type: dropdown
    id: frequency
    attributes:
      label: Bug Frequency
      description: How often does this bug occur?
      options:
        - Always (100%)
        - Often (75-99%)
        - Sometimes (25-74%)
        - Rarely (1-24%)
        - Unable to reproduce
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system unusable)
        - High (major functionality affected)
        - Medium (some functionality affected)
        - Low (minor issue)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: |
        - Related issues or PRs
        - Workarounds you've tried
        - Impact on your use case
        - Configuration details

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help?
      options:
        - label: I am willing to submit a pull request to fix this bug
        - label: I am available for testing the fix
